---
- name: Configure Environment
  hosts: all
  become: yes
  become_user: root
  vars:
    image: ""
    ansible_python_interpreter: /usr/bin/python3
    docker_host_env:
      DOCKER_HOST: "unix:///var/run/docker.sock"

  tasks:
    - name: Pull application Docker image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull
      environment: "{{ docker_host_env }}"

    - name: Stop existing container (if running)
      community.docker.docker_container:
        name: app_container
        state: absent
        force_kill: true
      environment: "{{ docker_host_env }}"

    - name: Run application container
      community.docker.docker_container:
        name: app_container
        image: "{{ image }}"
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
      environment: "{{ docker_host_env }}"
