---
- name: Configure EC2 Instance for Docker, Ansible, and Monitoring (Simple)
  hosts: all
  become: yes

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3
          - python3-pip
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Install Docker Python SDK globally (system-wide)
      pip:
        name: docker
        executable: pip3

    - name: Install community.docker Ansible collection
      command: ansible-galaxy collection install community.docker
      args:
        creates: /root/.ansible/collections/ansible_collections/community/docker

    # Node Exporter setup
    - name: Create /opt directory
      file:
        path: /opt
        state: directory
        mode: '0755'

    - name: Download Node Exporter
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /opt/node_exporter-1.7.0.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Node Exporter
      unarchive:
        src: /opt/node_exporter-1.7.0.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Move Node Exporter binary
      copy:
        src: /opt/node_exporter-1.7.0.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        mode: '0755'
        remote_src: yes

    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/node_exporter
          User=root

          [Install]
          WantedBy=default.target
        mode: '0644'

    - name: Enable and start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
        daemon_reload: yes
